---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Add Vim 8 repository
    apt_repository:
      repo: ppa:jonathonf/vim
      codename: xenial

  - name: Install Vim 8
    apt: name=vim state=latest

  - shell: which direnv
    register: direnv_installed
    changed_when: false
    ignore_errors: true

  - name: Install Direnv
    get_url:
      url: https://github.com/direnv/direnv/releases/download/v2.11.3/direnv.linux-amd64
      dest: /usr/local/bin/direnv
      mode: 0755
    when: direnv_installed.rc != 0

  - name: Install peco
    unarchive:
      src: https://github.com/peco/peco/releases/download/v0.5.3/peco_linux_amd64.tar.gz
      remote_src: yes
      dest: /usr/local/bin
      extra_opts:
        - --strip=1
        - peco_linux_amd64/peco

  - name: Install GQH
    unarchive:
      src: https://github.com/motemen/ghq/releases/download/v0.8.0/ghq_linux_amd64.zip
      remote_src: yes
      dest: /usr/local/bin

